### ISSUE TITLE
Parameter requirements in workflows (descarteslabs 1.4.0) not well documented, new requirements since 1.2.0 

### ISSUE THREAD

**Issue by jens2121** [descarteslabs/descarteslabs-python#238]
## Expected Behavior
Expected the documentation to provide an example of the changes in how to use workflows since new changes have been implemented.

## Previous Behaviour of v1.2.0 which worked in 1.2.0 (and now no longer works)

```
workflow = wf.publish(result)
workflow.id
```

## Actual Behavior #1
Documentation says:
```
# continuing from previous example, where `result` is an `Int` proxy object
workflow = result.publish(name="one-plus-one", description="The result of 1 plus 1")
workflow.id

workflow.type
```
However, with this implementation we have a parameter that is not recognized... from the code definition it seems that "name" is meant to be "title"

`_publish_mixin() got an unexpected keyword argument 'name'`

## Actual Behavior #2
```
# continuing from previous example, where `result` is an `Int` proxy object
workflow = result.publish(title="one-plus-one", description="The result of 1 plus 1")
workflow.id

workflow.type
```
However this does also not work, and requires further parameters:

`_publish_mixin() missing 2 required positional arguments: 'id' and 'version'`

What are these parameters and how should they be treated?

## Severity
High

**Comment by stephaniegott** [comment]
As of version `1.4.0`, `wf.publish` has a new signature. Please see [the docs](https://docs.descarteslabs.com/descarteslabs/workflows/docs/execution.html#descarteslabs.workflows.models.publish) for more information. We have updated the [changelog](https://github.com/descarteslabs/descarteslabs-python#workflows---changed) to reflect these breaking changes. Additionally, `wf.publish` will still work with the old signature on version `1.3.0`.
